import { brand } from "./brand";

export const siteCopy = {
  hero: {
    eyebrow: "Fresh coffee. Chill energy.",
    headline: brand.headline,
    body: "Fresh coffee for slow mornings, big ideas, road trips, smoke sessions, beach days, and wherever the current takes you.",
    primaryCta: "Shop the Coffee",
    primaryHref: "/shop",
    secondaryCta: "Join the Crew",
    secondaryHref: "/#join-the-crew",
    microcopy: "No weird hype. Just coffee worth waking up for.",
  },
  featured: {
    eyebrow: "Find your flow",
    heading: "Pick your morning mood.",
    body: "Smooth, bold, bright, dark, or somewhere beautifully in the middle. Find the roast that fits today’s vibe.",
    shopAll: "Shop all coffee",
    empty:
      "Coffee will appear here once the Shopify catalog is connected. Until then, the tide is still coming in.",
    cardCta: "View the Roast",
  },
  tasteFinder: {
    eyebrow: "Taste finder",
    heading: "What kind of morning are we having?",
    body: "Four easy directions. Pick the pace that matches today’s vibe.",
  },
  subscriptions: {
    eyebrow: "Autopilot for your coffee",
    heading: "Never run aground.",
    body: "Choose your coffee, set your schedule, and let fresh bags keep showing up like a tiny monthly miracle.",
    primaryCta: "Explore Subscriptions",
    primaryHref: "/shop?subscription=true",
    note: "Available options and savings depend on the selected coffee.",
    fallbackBody:
      "Recurring delivery options will appear on product pages once Shopify selling plans are configured. Until then, stock up and keep your cup full.",
    fallbackCta: "Shop the Coffee",
    fallbackHref: "/shop",
  },
  brewGuidesPreview: {
    eyebrow: "Brew without overthinking it",
    heading: "Better coffee. Less confusion.",
    body: "Simple guides that help you make a better cup without turning your kitchen into a chemistry lab.",
    cta: "Explore Brew Guides",
    allGuides: "All guides",
  },
  newsletter: {
    eyebrow: "Join the crew",
    heading: "Good coffee news, occasionally.",
    body: "Get fresh drops, brewing tips, behind-the-scenes updates, and the occasional thought that probably started over coffee.",
    emailPlaceholder: "your@email.com",
    nameLabel: "Name",
    emailLabel: "Email",
    phoneLabel: "Phone (optional)",
    button: "Catch the Next Drop",
    firstOrderButton: "Get First-Order Updates",
    consent:
      "By signing up, you agree to receive marketing emails from Wake N’ Bake Coffee Co. You can unsubscribe anytime.",
    smsConsent: "Text me occasional offers (optional, unchecked by default).",
    success: "You’re in, dude.",
    successSupport: "We’ll keep you posted when something fresh washes ashore.",
    error: "Whoa. Something drifted off course.",
    errorSupport: "Give it another shot, or come back after the tide changes.",
    loading: "Signing you up…",
  },
  reviews: {
    heading: "From the shoreline",
    empty:
      "Customer stories will appear here after moderation. We do not display placeholder or fabricated reviews.",
  },
  cart: {
    navLabel: "Your Cart",
    drawerHeading: "Your Coffee Stash",
    emptyHeading: "Your cart is looking a little dry.",
    emptyBody: "Let’s get something fresh in there.",
    emptyCta: "Shop Coffee",
    subtotal: "Subtotal",
    checkout: "Head to Checkout",
    microcopy: "Taxes, shipping, and final discounts are calculated at checkout.",
    playfulTrust: "Breathe easy. Shopify handles the serious money stuff.",
    viewFullCart: "View full cart",
    discountPlaceholder: "Discount code",
    apply: "Apply",
    remove: "Remove",
    quantity: "Quantity",
    loading: "Loading your stash…",
    discountApplied: "applied",
    discountNotApplicable: "not applicable",
  },
  product: {
    addToCart: "Add to Cart",
    addedToStash: "Added to Your Stash",
    addedSupport: "Nice choice. Your morning is already looking better.",
    soldOut: "Sold out",
    soldOutHeading: "This roast drifted away.",
    soldOutBody: "It’s currently unavailable, but another batch may roll in soon.",
    variantUnavailable: "That option is currently out to sea.",
    keepItComing: "Keep It Coming",
    justThisBag: "Just This Bag",
    purchaseOptions: "Purchase options",
    quantity: "Quantity",
    relatedHeading: "You may also like",
    factsHeading: "In the cup",
    photoSoon: "Photo coming soon",
    photographySoon: "Product photography coming soon",
    fromPrice: "From",
  },
  shop: {
    heading: "Shop coffee",
    body: "Explore coffee for every kind of morning, from smooth and mellow to bold and adventurous.",
    emptyHeading: "Nothing washed ashore.",
    emptyBody: "Try another search, check the spelling, or browse all coffee.",
    emptyCta: "Browse All Coffee",
    clearFilters: "Clear filters",
    loadMore: "Load more",
    searchLabel: "Find Your Roast",
    searchPlaceholder: "Search coffee, roast, flavor, or vibe…",
  },
  search: {
    heading: "Find Your Roast",
    placeholder: "Search coffee, roast, flavor, or vibe…",
    noResultsHeading: "Nothing washed ashore.",
    noResultsBody: "Try another search, check the spelling, or browse all coffee.",
    browseAll: "Browse All Coffee",
  },
  contact: {
    heading: "Send a Message in a Bottle",
    body: "Questions, ideas, wholesale inquiries, or something wonderfully random? Send it our way.",
    firstName: "First Name",
    lastName: "Last Name",
    name: "Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    submit: "Send It Our Way",
    loading: "Sending it out to sea…",
    success: "Message received.",
    successSupport: "We’ll get back to you as soon as we can.",
    error: "That one did not make it.",
    errorSupport: "Please check your information and try again.",
  },
  notFound: {
    heading: "Looks like this page drifted out to sea.",
    body: "No worries. Even the best explorers take a wrong turn sometimes.",
    primaryCta: "Head Home",
    secondaryCta: "Shop Coffee",
    luna: brand.luna.notFound,
  },
  error: {
    heading: "Something drifted off course.",
    body: "We hit an unexpected wave loading this page. Try again, or head back to shore.",
    retry: "Try again",
  },
  consent: {
    body: "We use optional analytics and marketing cookies to improve the storefront. No optional scripts load until you choose. Checkout still happens securely on Shopify.",
    acceptAll: "Accept analytics & marketing",
    analyticsOnly: "Analytics only",
    reject: "Reject optional",
  },
  footer: {
    tagline: brand.headline,
    trust: "DAV supporter. Veteran owned. Checkout secured by Shopify.",
  },
  brewGuidesIndex: {
    heading: "Brew guides",
    body: "Simple guides that help you make a better cup without turning your kitchen into a chemistry lab.",
  },
  journal: {
    heading: "Coffee journal",
    body: "Brew tips, coffee basics, camp coffee, road-trip kits, and behind-the-brand stories — written for people who want better coffee without the lecture.",
    readMore: "Read the Guide",
  },
  wholesale: {
    heading: "Wholesale",
    body: "Serving a cafe, market, or hospitality program? Tell us about your volume and we will follow up with availability through our Shopify and Dripshipper channel.",
    note: "Pricing and MOQs are confirmed after review — we do not publish unverified wholesale claims on this page.",
    firstOrderHeading: "Join the crew",
    firstOrderBody:
      "Get updates when first-order offers and fresh drops are active. No weird energy. Unsubscribe anytime.",
  },
  orderStates: {
    confirmationHeading: "You’re officially brewing.",
    confirmationBody:
      "Your order is in. We’ll send updates as it moves through the process.",
    shippingHeading: "Your coffee caught a wave.",
    deliveryHeading: "It made it ashore.",
  },
} as const;
